spring:
  datasource:
      master:
            driver-class-name: com.mysql.jdbc.Driver
            type: com.zaxxer.hikari.HikariDataSource
            jdbcUrl: jdbc:mysql://127.0.0.1:3306/db1?characterEncoding=utf-8&useSSL=false
            username: root
            password:
      slave:
            driver-class-name: com.mysql.jdbc.Driver
            type: com.zaxxer.hikari.HikariDataSource
            jdbcUrl: jdbc:mysql://127.0.0.1:3306/db2?characterEncoding=utf-8&useSSL=false
            username: root
            password:

mybatis:
    type-aliases-package: com.avanty.mapper
    mapper-locations: classpath:mapper/*Mapper.xml
